SET IDENTITY_INSERT [dbo].[RATINGS] ON
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (1, 3, N'Great!', N'Black Panther')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (2, 4, N'I edge to Adele', N'21')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (3, 5, N'Excellent!', N'SOS')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (4, 3, N'Nice!', N'Speak Now')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (5, 5, N'Will buy more from Olivia!', N'Sour')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (6, 3, N'Adele is best!', N'21')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (7, 2, N'Ed is the best!', N'Divide')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (8, 5, N'', N'?')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (9, 5, N'', N'The Album')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (10, 5, N'Great Job Disney!', N'The Lion King')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (11, 5, N'', N'Born To Die')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (12, 2, N'GOAT MJ!', N'Thriller')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (13, 5, N'Very Good!!', N'Born Pink')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (14, 5, N'', N'Fearless')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (15, 5, N'', N'Map of the Soul: Persona')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (16, 5, N'Perfect', N'The Dark Side of the Moon')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (17, 5, N'', N'The Dark Side of the Moon')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (18, 3, N'', N'Parachutes')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (19, 2, N'Can be improved by Coldplay!', N'Yellow')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (20, 4, N'', N'Music of the Spheres')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (21, 3, N'', N'30')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (22, 1, N'Goofy ahh song', N'X')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (23, 4, N'Jonas Brothers are the best', N'The Album')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (24, 5, N'Eminem...', N'Curtain Call: The Hits')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (25, 5, N'OG GOAT BY 50cent', N'Get Rich or Die Tryin')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (26, 3, N'Dre never miss!', N'2001')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (27, 2, N'One of the best!', N'Me Against The World')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (28, 5, N'Kanye > Taylor', N'Graduation ')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (29, 4, N'My first Tyler album', N'IGOR')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (30, 5, N'Taylor is still the best!', N'Folklore')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (31, 4, N'My favourtie ts album', N'Folklore')
INSERT INTO [dbo].[RATINGS] ([RatingID], [rating], [review], [Title]) VALUES (32, 5, N'nice', N'Made in the AM')
SET IDENTITY_INSERT [dbo].[RATINGS] OFF
